// <auto-generated />
using System;
using Mas.Domain.UserCenter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mas.Domain.UserCenter.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20181024061311_UserCenter")]
    partial class UserCenter
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mas.Domain.Common.User.Sys_User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30);

                    b.Property<DateTime>("Created");

                    b.Property<string>("CreatorId");

                    b.Property<string>("CreatorName");

                    b.Property<string>("HeadPhoto");

                    b.Property<string>("IdCard")
                        .HasMaxLength(18);

                    b.Property<string>("LoginName")
                        .HasMaxLength(30);

                    b.Property<string>("Mobile")
                        .HasMaxLength(16);

                    b.Property<DateTime>("Modified");

                    b.Property<string>("ModifierId");

                    b.Property<string>("ModifierName");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .HasMaxLength(32);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<int>("State");

                    b.Property<string>("UserName")
                        .HasMaxLength(30);

                    b.Property<string>("WeChatNum");

                    b.HasKey("Id");

                    b.ToTable("Sys_User");
                });
#pragma warning restore 612, 618
        }
    }
}
